version: 0.2

phases:
  install:
    runtime-versions:
      kubernetes: 1.23 # Specify the Kubernetes version you're using
    commands:
      - echo "Installing kubectl"
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - sudo mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo "Configuring kubectl for EKS..."
      - aws eks update-kubeconfig --name YOUR_EKS_CLUSTER_NAME --region YOUR_AWS_REGION
      # Verify connection
      - kubectl config current-context
      - kubectl get nodes

  build:
    commands:
      - echo "Deploying to Kubernetes..."
      - kubectl apply -f kubernetes/deployment.yaml
      - kubectl apply -f kubernetes/service.yaml
      #  Optional: Wait for deployment to complete (add more robust checks if needed)
      - kubectl rollout status deployment/my-nodejs-app-deployment --timeout=300s

artifacts:
    files: []